AZURE_SEND_GRID = 'AZURE_SEND_GRID'
DATABASE_HOST_SERVER = 'DATABASE_HOST_SERVER'
DATABASE_PASSWORD = 'DATABASE_PASSWORD'
DATABASE_NAME = 'DATABASE_NAME'
DATABASE_USER = 'DATABASE_USER'
DJANGO_SECRET_KEY = 'DJANGO_SECRET_KEY'
TMDB_API_KEY = 'TMDB_API_KEY'

SOCIAL_AUTH_TWITTER_KEY = 'SOCIAL_AUTH_TWITTER_KEY'
SOCIAL_AUTH_TWITTER_SECRET = 'SOCIAL_AUTH_TWITTER_SECRET'

SOCIAL_AUTH_FACEBOOK_KEY = 'SOCIAL_AUTH_FACEBOOK_KEY'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'SOCIAL_AUTH_FACEBOOK_SECRET'


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'SOCIAL_AUTH_GOOGLE_OAUTH2_KEY'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET'
