# Generated by Django 2.1.1 on 2018-09-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0002_user_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateofbirth',
            field=models.DateField(default='1992-01-01'),
        ),
    ]
