# Generated by Django 2.1.1 on 2018-09-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0005_user_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
