# Generated by Django 2.1.1 on 2018-09-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0006_auto_20180930_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.TextField(blank=True),
        ),
    ]
