# Generated by Django 2.1.1 on 2018-10-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0008_auto_20181020_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
