# Generated by Django 2.1.1 on 2018-10-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0010_auto_20181020_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isFirstLogin',
            field=models.BooleanField(default=1),
        ),
    ]
