# Generated by Django 2.1.1 on 2018-10-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0011_userprofile_isfirstlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.TextField(blank=True)),
                ('belongs_to_collection', models.TextField(blank=True)),
                ('budget', models.TextField(blank=True)),
                ('genres', models.TextField(blank=True)),
                ('homepage', models.TextField(blank=True)),
                ('movie_id', models.TextField(blank=True)),
                ('imdb_id', models.TextField(blank=True)),
                ('original_language', models.TextField(blank=True)),
                ('original_title', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('popularity', models.TextField(blank=True)),
                ('poster_path', models.TextField(blank=True)),
                ('production_companies', models.TextField(blank=True)),
                ('production_countries', models.TextField(blank=True)),
                ('release_date', models.TextField(blank=True)),
                ('revenue', models.TextField(blank=True)),
                ('runtime', models.TextField(blank=True)),
                ('spoken_languages', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('tagline', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('video', models.TextField(blank=True)),
                ('vote_average', models.TextField(blank=True)),
                ('vote_count', models.TextField(blank=True)),
            ],
        ),
    ]
