# Generated by Django 2.1.1 on 2018-10-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0013_auto_20181027_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('genre', models.TextField(null=True)),
            ],
        ),
    ]
