# Generated by Django 2.1.1 on 2018-10-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0014_moviegenre'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenreList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genreid', models.TextField(null=True)),
                ('genre', models.TextField(null=True)),
            ],
        ),
    ]
