# Generated by Django 2.1.1 on 2018-10-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0015_moviegenrelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenreSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('Action', models.BooleanField(null=True)),
                ('Adventure', models.BooleanField(null=True)),
                ('Animation', models.BooleanField(null=True)),
                ('Comedy', models.BooleanField(null=True)),
                ('Crime', models.BooleanField(null=True)),
                ('Documentary', models.BooleanField(null=True)),
                ('Drama', models.BooleanField(null=True)),
                ('Family', models.BooleanField(null=True)),
                ('Fantasy', models.BooleanField(null=True)),
                ('History', models.BooleanField(null=True)),
                ('Horror', models.BooleanField(null=True)),
                ('Music', models.BooleanField(null=True)),
                ('Mystery', models.BooleanField(null=True)),
                ('Romance', models.BooleanField(null=True)),
                ('Science', models.BooleanField(null=True)),
                ('TV', models.BooleanField(null=True)),
                ('Thriller', models.BooleanField(null=True)),
                ('War', models.BooleanField(null=True)),
                ('Western', models.BooleanField(null=True)),
            ],
        ),
    ]
