# Generated by Django 2.1.1 on 2018-10-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0016_moviegenreselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegenreselection',
            name='popularity',
            field=models.FloatField(null=True),
        ),
    ]
