# Generated by Django 2.1.1 on 2018-10-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0017_moviegenreselection_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegenreselection',
            name='tmdbId',
            field=models.TextField(null=True),
        ),
    ]
