# Generated by Django 2.1.1 on 2018-10-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0019_userselectmovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselectmovies',
            name='user',
        ),
        migrations.AddField(
            model_name='userselectmovies',
            name='userId',
            field=models.TextField(null=True),
        ),
    ]
