# Generated by Django 2.1.1 on 2018-11-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0021_auto_20181028_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselectmovies',
            name='movieName',
            field=models.TextField(null=True),
        ),
    ]
