# Generated by Django 2.1.1 on 2018-11-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0022_userselectmovies_moviename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselectmovies',
            name='isMovieRec',
            field=models.BooleanField(default=False),
        ),
    ]
