# Generated by Django 2.1.1 on 2018-11-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0023_userselectmovies_ismovierec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselectmovies',
            old_name='movieId',
            new_name='tmdbId',
        ),
    ]
