# Generated by Django 2.1.1 on 2018-11-21 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0024_auto_20181121_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviegenreselection',
            name='History',
        ),
    ]
