# Generated by Django 2.1.1 on 2018-11-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0026_moviegenreselection_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviegenreselection',
            name='History',
        ),
        migrations.AddField(
            model_name='moviegenreselection',
            name='voteavg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='moviegenreselection',
            name='votecount',
            field=models.FloatField(null=True),
        ),
    ]
