# Generated by Django 2.1.1 on 2018-11-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimefinder', '0027_auto_20181123_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('flag', models.TextField(null=True)),
                ('userId', models.TextField(null=True)),
                ('imdb_id', models.TextField(null=True)),
                ('year', models.TextField(null=True)),
                ('popularity', models.TextField(null=True)),
                ('original_movie', models.TextField(null=True)),
                ('time_stamp', models.DateField(null=True)),
            ],
        ),
    ]
